### ISSUE TITLE
no matches for kind "Application" in version "app.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by 2498884969** [shikanon/kubeflow-manifests#16]
unable to recognize "application.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
unable to recognize "argo.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "centraldashboard.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-install.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "logentry" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "logentry" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-install.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-install.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "ServiceEntry" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "ServiceEntry" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "istio.yaml": no matches for kind "ClusterRbacConfig" in version "rbac.istio.io/v1alpha1"
unable to recognize "jupyter-web-app.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
unable to recognize "jupyter-web-app.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "katib-ui.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "metadata.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "notebook-controller.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
unable to recognize "pipelines-ui.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "pipelines-ui.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "profiles.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "seldon-core-operator.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"
unable to recognize "tensorboard.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "tf-job-operator.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"

**Comment by shikanon** [comment]
@2498884969 your cluster has istio be installed? the problem seem istio resource is not match
