### ISSUE TITLE
kubectl apply时出现以下错误

### ISSUE THREAD

**Issue by zhuzhengqiang317** [shikanon/kubeflow-manifests#21]
Resource: "apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"
Name: "orders.acme.cert-manager.io", Namespace: ""
for: "./manifest1.3/002-cert-manager-cert-manager-crds-base.yaml": CustomResourceDefinition.apiextensions.k8s.io "orders.acme.cert-manager.io" is invalid: status.storedVersions[1]: Invalid value: "v1": must appear in spec.versions

**Comment by shikanon** [comment]
你的k8s版本是？

**Comment by zhuzhengqiang317** [comment]
1.18.2

**Comment by shikanon** [comment]
我看了下`orders.acme.cert-manager.io`的version是`version: v1alpha2`，而不是你这里的`v1`，是不是你之前装了cert manager，你可以先将crd资源删除再安装试试：
```
kubectl delete -f ./manifest1.3
python install.py
```

**Comment by zhuzhengqiang317** [comment]
好的我试一下
