### ISSUE TITLE
重新挂起虚拟机就无法访问WEB UI了

### ISSUE THREAD

**Issue by nongqiqin** [shikanon/kubeflow-manifests#30]
在虚拟机上成功安装之后，能够正确使用本地的30000端口访问页面，里面的功能也基本能使用
然后挂起虚拟机，在第二天重新开启虚拟机时就无法访问了，显示HTTP ERROR 403
我删除了po重新创建也没有解决
![image](https://user-images.githubusercontent.com/31816449/120948834-a9df0b00-c775-11eb-98dd-9209a68bf809.png)
pods 都是正常running状态的
![image](https://user-images.githubusercontent.com/31816449/120948857-b6fbfa00-c775-11eb-826d-ab5e8c78f9a9.png)
请问有办法解决吗？谢谢！

**Comment by shikanon** [comment]
@nongqiqin 你的k8s可以正常运行吗，看你得截图系统组件重启了很多次，你可以用 port-forward 直接连服务看是否有界面信息返回：
```bash
kubectl -nistio-system  port-forward service/cluster-local-gateway 
```

**Comment by nongqiqin** [comment]
> @nongqiqin 你的k8s可以正常运行吗，看你得截图系统组件重启了很多次，你可以用 port-forward 直接连服务看是否有界面信息返回：
> 
> ```shell
> kubectl -nistio-system  port-forward service/cluster-local-gateway 
> ```

不太明白，你这段命令也没法执行，少了端口号吗？而且重启很多次大部分是因为拉不到镜像失败了重启

**Comment by nongqiqin** [comment]
> @nongqiqin 你的k8s可以正常运行吗，看你得截图系统组件重启了很多次，你可以用 port-forward 直接连服务看是否有界面信息返回：
> 
> ```shell
> kubectl -nistio-system  port-forward service/cluster-local-gateway 
> ```

查kubeflow issue 403，好像有人说是authservice的问题，我delete  oidc-authservice-oidc-authservice-base.yaml 是可以出现界面的，但是里面的组件又不能正常显示

**Comment by shikanon** [comment]
@nongqiqin 端口就是cluster-local-gateway暴露的端口，你可以看看service的端口号。

我看你的截图怎么没有 `auth`的命名空间，是不是你删掉了？还是截图没截到？你重装下 patch 文件夹试试：
```bash
kubectl delete -f patch/
kubectl apply -f patch/
```
