### ISSUE TITLE
error: unable to recognize "017-pipeline-env-platform-agnostic-multi-user.yaml": no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by weiwei-9527** [shikanon/kubeflow-manifests#31]
我用的是tke-1.18.4的k8s，是我用的版本太老了吗

**Comment by shikanon** [comment]
集群是支持k8s 1.18版本得，是不是之前你安装过这类型得CRD，你可以尝试先delete再apply:
```yaml
kubectl delete -f manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml
kubectl apply -f manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml
```

**Comment by weiwei-9527** [comment]
我是新建的集群

**Comment by jacklee999** [comment]
> 我是新建的集群

我也报同样的错，你有没有解决这个问题。

**Comment by weiwei-9527** [comment]
> > 我是新建的集群
> 
> 我也报同样的错，你有没有解决这个问题。

没有，暂时搁置了，过两天还得弄

**Comment by shikanon** [comment]
@jacklee999 @weiwei-9527 你可以可以输出`compositecontrollers`这个 crd 看看嘛？
```bash
$ kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
```

**Comment by weiwei-9527** [comment]
> @jacklee999 @weiwei-9527 你可以输出`compositecontrollers`这个 crd 看看嘛？
> 
> ```shell
> $ kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
> ```

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"application-crd-id":"kubeflow-pipelines","kustomize.component":"metacontroller"},"name":"compositecontrollers.metacontroller.k8s.io"},"spec":{"group":"metacontroller.k8s.io","names":{"kind":"CompositeController","plural":"compositecontrollers","shortNames":["cc","cctl"],"singular":"compositecontroller"},"scope":"Cluster","version":"v1alpha1"}}
  creationTimestamp: "2021-06-21T07:15:37Z"
  generation: 1
  labels:
    application-crd-id: kubeflow-pipelines
    kustomize.component: metacontroller
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2021-06-21T07:15:37Z"
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:application-crd-id: {}
          f:kustomize.component: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:version: {}
        f:versions: {}
      f:status:
        f:storedVersions: {}
    manager: kubectl
    operation: Update
    time: "2021-06-21T07:15:37Z"
  name: compositecontrollers.metacontroller.k8s.io
  resourceVersion: "10636"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/compositecontrollers.metacontroller.k8s.io
  uid: 1f4cd2a0-9b52-4080-a304-8b14f8310646
spec:
  conversion:
    strategy: None
  group: metacontroller.k8s.io
  names:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  preserveUnknownFields: true
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  conditions:
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: protected groups must have approval annotation "api-approved.kubernetes.io",
      see https://github.com/kubernetes/enhancements/pull/1111
    reason: MissingAnnotation
    status: "False"
    type: KubernetesAPIApprovalPolicyConformant
  storedVersions:
  - v1alpha1

**Comment by weiwei-9527** [comment]
@shikanon 
`apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"application-crd-id":"kubeflow-pipelines","kustomize.component":"metacontroller"},"name":"compositecontrollers.metacontroller.k8s.io"},"spec":{"group":"metacontroller.k8s.io","names":{"kind":"CompositeController","plural":"compositecontrollers","shortNames":["cc","cctl"],"singular":"compositecontroller"},"scope":"Cluster","version":"v1alpha1"}}
  creationTimestamp: "2021-06-21T07:15:37Z"
  generation: 1
  labels:
    application-crd-id: kubeflow-pipelines
    kustomize.component: metacontroller
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2021-06-21T07:15:37Z"
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:application-crd-id: {}
          f:kustomize.component: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:version: {}
        f:versions: {}
      f:status:
        f:storedVersions: {}
    manager: kubectl
    operation: Update
    time: "2021-06-21T07:15:37Z"
  name: compositecontrollers.metacontroller.k8s.io
  resourceVersion: "10636"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/compositecontrollers.metacontroller.k8s.io
  uid: 1f4cd2a0-9b52-4080-a304-8b14f8310646
spec:
  conversion:
    strategy: None
  group: metacontroller.k8s.io
  names:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  preserveUnknownFields: true
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  conditions:
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: protected groups must have approval annotation "api-approved.kubernetes.io",
      see https://github.com/kubernetes/enhancements/pull/1111
    reason: MissingAnnotation
    status: "False"
    type: KubernetesAPIApprovalPolicyConformant
  storedVersions:
  - v1alpha1
`

**Comment by weiwei-9527** [comment]
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"application-crd-id":"kubeflow-pipelines","kustomize.component":"metacontroller"},"name":"compositecontrollers.metacontroller.k8s.io"},"spec":{"group":"metacontroller.k8s.io","names":{"kind":"CompositeController","plural":"compositecontrollers","shortNames":["cc","cctl"],"singular":"compositecontroller"},"scope":"Cluster","version":"v1alpha1"}}
  creationTimestamp: "2021-06-21T07:15:37Z"
  generation: 1
  labels:
    application-crd-id: kubeflow-pipelines
    kustomize.component: metacontroller
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2021-06-21T07:15:37Z"
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:application-crd-id: {}
          f:kustomize.component: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:version: {}
        f:versions: {}
      f:status:
        f:storedVersions: {}
    manager: kubectl
    operation: Update
    time: "2021-06-21T07:15:37Z"
  name: compositecontrollers.metacontroller.k8s.io
  resourceVersion: "10636"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/compositecontrollers.metacontroller.k8s.io
  uid: 1f4cd2a0-9b52-4080-a304-8b14f8310646
spec:
  conversion:
    strategy: None
  group: metacontroller.k8s.io
  names:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  preserveUnknownFields: true
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  conditions:
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: protected groups must have approval annotation "api-approved.kubernetes.io",
      see https://github.com/kubernetes/enhancements/pull/1111
    reason: MissingAnnotation
    status: "False"
    type: KubernetesAPIApprovalPolicyConformant
  storedVersions:
  - v1alpha1

```

**Comment by weiwei-9527** [comment]
@shikanon 
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"labels":{"application-crd-id":"kubeflow-pipelines","kustomize.component":"metacontroller"},"name":"compositecontrollers.metacontroller.k8s.io"},"spec":{"group":"metacontroller.k8s.io","names":{"kind":"CompositeController","plural":"compositecontrollers","shortNames":["cc","cctl"],"singular":"compositecontroller"},"scope":"Cluster","version":"v1alpha1"}}
  creationTimestamp: "2021-06-21T07:15:37Z"
  generation: 1
  labels:
    application-crd-id: kubeflow-pipelines
    kustomize.component: metacontroller
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2021-06-21T07:15:37Z"
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:application-crd-id: {}
          f:kustomize.component: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:version: {}
        f:versions: {}
      f:status:
        f:storedVersions: {}
    manager: kubectl
    operation: Update
    time: "2021-06-21T07:15:37Z"
  name: compositecontrollers.metacontroller.k8s.io
  resourceVersion: "10636"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/compositecontrollers.metacontroller.k8s.io
  uid: 1f4cd2a0-9b52-4080-a304-8b14f8310646
spec:
  conversion:
    strategy: None
  group: metacontroller.k8s.io
  names:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  preserveUnknownFields: true
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: CompositeController
    listKind: CompositeControllerList
    plural: compositecontrollers
    shortNames:
    - cc
    - cctl
    singular: compositecontroller
  conditions:
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2021-06-21T07:15:37Z"
    message: protected groups must have approval annotation "api-approved.kubernetes.io",
      see https://github.com/kubernetes/enhancements/pull/1111
    reason: MissingAnnotation
    status: "False"
    type: KubernetesAPIApprovalPolicyConformant
  storedVersions:
  - v1alpha1

```

**Comment by weiwei-9527** [comment]
@shikanon 
当我出现上面的那个报错后，我按照你说的，重新跑了一下就没有no  matches 这个问题了
```
kubectl delete -f manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml
kubectl apply -f manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml
```
但是我再delete的时候又出现了，似乎apply 的时候没有报出问题，但是资源并没有成功创建
```
Error from server (NotFound): error when deleting "017-pipeline-env-platform-agnostic-multi-user.yaml": the server could not find the requested resource (delete compositecontrollers.metacontroller.k8s.io kubeflow-pipelines-profile-controller)

```

**Comment by weiwei-9527** [comment]
@jacklee999 
我似乎装好了，但是我不能确定上面那个问题会不会有啥影响，就是我删除之后出现的报错
![image](https://user-images.githubusercontent.com/64568511/122727802-07ad4000-d2aa-11eb-93f0-32e71641ea81.png)

**Comment by shikanon** [comment]
@weiwei-9527 看你输出这个CRD应该是安装成功了，你 get CompositeController 看看：
```bash
$ kubectl get CompositeController -A
NAME                                    AGE
kubeflow-pipelines-profile-controller   41d
```
看是否存在`kubeflow-pipelines-profile-controller`这个对象。

**Comment by weiwei-9527** [comment]
@shikanon 
```
[root@10-6-4-74 kubeflow-manifests]# kubectl get CompositeController -A
NAME                                    AGE
kubeflow-pipelines-profile-controller   24m

```

**Comment by shikanon** [comment]
@weiwei-9527 这样看你这个没有问题啊，这个deployment `kubeflow-pipelines-profile-controller` 起来了嘛：
```bash
$ kubectl get po -nkubeflow | grep pipelines-profile
kubeflow-pipelines-profile-controller-5698bf57cf-btpn5      1/1     Running   0          39d
kubeflow-pipelines-profile-controller-5698bf57cf-vs8rh      1/1     Running   0          34d
```

**Comment by weiwei-9527** [comment]
@shikanon 也起来了
```
[root@10-6-4-74 kubeflow-manifests]# kubectl get po -nkubeflow | grep pipelines-profile
kubeflow-pipelines-profile-controller-85d6ff7d6c-fq5cd       1/1     Running   0          22m

```

**Comment by shikanon** [comment]
@weiwei-9527 那你这个 profile controller 应该是运行成功了，现在系统还存在什么问题

**Comment by weiwei-9527** [comment]
@shikanon 暂时看不出什么问题，得使用之后才能知道，感谢帮助

**Comment by Corezcy** [comment]
> 集群是支持k8s 1.18版本得，是不是之前你安装过这类型得CRD，你可以尝试先delete再apply:
> 
> ```yaml
> kubectl delete -f manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml
> kubectl apply -f manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml
> ```

请问1.20的版本支持吗？

**Comment by shikanon** [comment]
@Corezcy 最新版本已经支持k8s 1.20版本了

**Comment by lesserror** [comment]
> @jacklee999 @weiwei-9527 你可以输出`compositecontrollers`这个 crd 看看嘛？
> 
> ```shell
> $ kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
> ```
您好，我查询不到这个`crd`是怎么回事呢？
```shell
root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get CompositeController -A
    error: the server doesn't have a resource type "CompositeController"

root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
    Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "compositecontrollers.metacontroller.k8s.io" not found

```

**Comment by shikanon** [comment]
> > @jacklee999 @weiwei-9527 你可以输出`compositecontrollers`这个 crd 看看嘛？
> > ```shell
> > $ kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
> > ```
> 
> @shikanon 您好，我查询不到这个`crd`是怎么回事呢？另外说明一下，我是在用`kubeadm`搭建的k8s集群上进行部署的，麻烦大家指教一下
> 
> ```shell
> root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get CompositeController -A
>     error: the server doesn't have a resource type "CompositeController"
> 
> root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
>     Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "compositecontrollers.metacontroller.k8s.io" not found
> ```

说明没安装成功，crd是资源最基础的文件，你可以卸载重新安装

**Comment by lesserror** [comment]
> > > @jacklee999 @weiwei-9527 你可以输出`compositecontrollers`这个 crd 看看嘛？
> > > ```shell
> > > $ kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
> > > ```
> > 
> > 
> > @shikanon 您好，我查询不到这个`crd`是怎么回事呢？另外说明一下，我是在用`kubeadm`搭建的k8s集群上进行部署的，麻烦大家指教一下
> > ```shell
> > root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get CompositeController -A
> >     error: the server doesn't have a resource type "CompositeController"
> > 
> > root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
> >     Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "compositecontrollers.metacontroller.k8s.io" not found
> > ```
> 
> 说明没安装成功，crd是资源最基础的文件，你可以卸载重新安装

可是我删除又重装，017这个yaml文件一直报以下错误呢：
`error: unable to recognize "manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml": no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"`，没法正常安装上。

**Comment by zengqingfu1442** [comment]
> > @jacklee999 @weiwei-9527 你可以输出`compositecontrollers`这个 crd 看看嘛？
> > ```shell
> > $ kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
> > ```
> 
> @shikanon 您好，我查询不到这个`crd`是怎么回事呢？另外说明一下，我是在用`kubeadm`搭建的k8s集群上进行部署的，麻烦大家指教一下
> 
> ```shell
> root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get CompositeController -A
>     error: the server doesn't have a resource type "CompositeController"
> 
> root@master:/home/hqc/Kubeflow/Kubeflow1.3# kubectl get crd compositecontrollers.metacontroller.k8s.io -oyaml
>     Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "compositecontrollers.metacontroller.k8s.io" not found
> ```

我也遇到同样的问题，请问您怎么解决的？

**Comment by zengqingfu1442** [comment]
试了下，k8s 1.16 --> 1.22 之间的没有这个问题。
