### ISSUE TITLE
unable to create new content in namespace kubeflow because it is being terminated

### ISSUE THREAD

**Issue by kangzhang0709** [shikanon/kubeflow-manifests#39]
kubectl apply -f ./manifest1.3/023-jupyter-overlays-kubeflow.yaml
Error from server (Forbidden): error when creating "./manifest1.3/023-jupyter-overlays-kubeflow.yaml": serviceaccounts "notebook-controller-service-account" is forbidden: unable to create new content in namespace kubeflow because it is being terminated

**Comment by shikanon** [comment]
你应该是 delete kubeflow 命名空间吧，这个命名空间在退出过程中，你 apply 再创建就不生效，你可以看看kubeflow命名空间状态:
```bash
kubectl get ns
```

**Comment by kangzhang0709** [comment]
> 你应该是 delete kubeflow 命名空间吧，这个命名空间在退出过程中，你 apply 再创建就不生效，你可以看看kubeflow命名空间状态:
> 
> ```shell
> kubectl get ns
>
