### ISSUE TITLE
运行之后功能不可用

### ISSUE THREAD

**Issue by mockdone** [shikanon/kubeflow-manifests#4]
点击左侧菜单，右侧功能均不可用  Sorry, /pipeline/ is not a valid page

**Comment by shikanon** [comment]
是不是pipeline没有起来，你可以用kubectl查看下

**Comment by lesserror** [comment]
> 是不是pipeline没有起来，你可以用kubectl查看下

我的也是呢，因为017个文件部署出现错误，pipeine，没有起来。
所以要怎么处理呢？有没有同样遇到已经解决了的小伙伴

**Comment by shikanon** [comment]
@lesserror 017文件报什么错？

**Comment by lesserror** [comment]
> @lesserror 017文件报什么错？
报的这个错：
`error: unable to recognize "manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml": no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"
然后我多方尝试解决不了之后，就尝试把这个文件中含CompositeController这个词的部分注释掉了，重新部署竟然成功了（UI中也可以正常显示），但就是不知道后续会不会有什么问题，因为只是单纯注释了没做其他改变

后续会因为这个遇到什么问题嘛？我还没有尝试

**Comment by shikanon** [comment]
> > @lesserror 017文件报什么错？
> 
> @shikanon 您好~ 报的这个错： `error: unable to recognize "manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml": no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"` 然后我多方尝试解决不了之后，就尝试把这个文件中含CompositeController这个词的部分注释掉了，重新部署竟然成功了（UI中也可以正常显示），但就是不知道后续会不会有什么问题，因为只是单纯注释了没做其他改变
> 
> 后续会因为这个遇到什么问题嘛？我还没有尝试

`no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"` 说明crd安装失败了，看看是不是版本不兼容，这个会影响后面使用的，这个问题有人已经解决，你可以在issue翻翻
