### ISSUE TITLE
CopyFile() is not implemented in the k8sapi executor.

### ISSUE THREAD

**Issue by nongqiqin** [shikanon/kubeflow-manifests#41]
想问一下大佬这是什么问题
![image](https://user-images.githubusercontent.com/31816449/124686716-2b0cf780-df06-11eb-892c-2cfe3802e483.png)
好像kubeflow 1.3版本以下都没有这个问题？

Kubernetes 版本: v1.19.12
kubeflow版本：1.3

**Comment by shikanon** [comment]
@nongqiqin 我的 argo 使用的 k8sapi 做 executor，如果你需要使用 copyfile 这类功能可以换成 docker 做 executor，具体原因在这里有说明：https://github.com/shikanon/kubeflow-manifests/blob/master/docs/introduction.md

**Comment by nongqiqin** [comment]
> @nongqiqin 我的 argo 使用的 k8sapi 做 executor，如果你需要使用 copyfile 这类功能可以换成 docker 做 executor，具体原因在这里有说明：https://github.com/shikanon/kubeflow-manifests/blob/master/docs/introduction.md#experiments-and-pipelines
OKOK，明白了
