### ISSUE TITLE
能不能说明一下k8s和kubeflow的版本

### ISSUE THREAD

**Issue by burger1221** [shikanon/kubeflow-manifests#5]
能不能说明一下k8s和kubeflow的版本

**Comment by ald2004** [comment]
# coding:utf-8
# wget -c https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
# wget https://github.com/kubeflow/kubeflow/releases/download/v0.6.2/kfctl_v0.6.2_linux.tar.gz
import os

data_dir = './manifests'
yaml_files = ['./cert-manager/cert-manager/base',
              './cert-manager/cert-manager-crds/base',
              './pipeline/persistent-agent/base', './pipeline/api-service/base',
              './pipeline/mysql/base', './pipeline/scheduledworkflow/base',
              './pipeline/pipelines-viewer/base',
              './pipeline/pipelines-runner/base', './pipeline/pipelines-ui/base',
              './pipeline/minio/base', './katib-v1alpha1/studyjob/base',
              './katib-v1alpha1/vizier-db/base',
              './katib-v1alpha1/suggestion/base',
              './katib-v1alpha1/katib-ui/base',
              './katib-v1alpha1/metrics-collector/base',
              './katib-v1alpha1/vizier-core/base',
              './pytorch-job/pytorch-job-crds/base',
              './pytorch-job/pytorch-operator/base', './istio/istio/base',
              './istio/istio-install/base', './istio/istio-crds/base',
              './tf-training/tf-job-operator/base',
              './katib-v1alpha2/katib-db/base',
              './katib-v1alpha2/katib-manager/base',
              './katib-v1alpha2/suggestion/base',
              './katib-v1alpha2/katib-ui/base',
              './katib-v1alpha2/katib-controller/base',
              './katib-v1alpha2/metrics-collector/base', './modeldb/base',
              './seldon/seldon-core-operator/base', './common/basic-auth/base',
              './common/spartakus/base', './common/centraldashboard/base',
              './common/ambassador/base', './kubebench/base',
              './argo/base', './tensorboard/base',
              './profiles/base', './admission-webhook/bootstrap/base',
              './admission-webhook/webhook/base', './metadata/base',
              './application/application-crds/base',
              './application/application/base',
              './jupyter/notebook-controller/base',
              './jupyter/jupyter-web-app/base', './jupyter/jupyter/base',
              './metacontroller/base', './gcp/basic-auth-ingress/base',
              './gcp/cloud-endpoints/base', './gcp/prometheus/base',
              './gcp/gpu-driver/base', './gcp/iap-ingress/base']
for fxname in yaml_files:
    filename = os.path.join(data_dir, fxname)
    cmd = "kubectl kustomize %s" % (filename)
    # print(cmd)
    with os.popen(cmd) as fr:
        with open(f"{data_dir}/yaml/{fxname.split('/')[-2]}.yaml", "w") as fw:
            data = fr.read()
            print(data)
            fw.write(data)
    # break

**Comment by ald2004** [comment]
``` python
# coding:utf-8
# wget -c https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
# wget https://github.com/kubeflow/kubeflow/releases/download/v0.6.2/kfctl_v0.6.2_linux.tar.gz
import os

data_dir = './manifests'
yaml_files = ['./cert-manager/cert-manager/base',
              './cert-manager/cert-manager-crds/base',
              './pipeline/persistent-agent/base', './pipeline/api-service/base',
              './pipeline/mysql/base', './pipeline/scheduledworkflow/base',
              './pipeline/pipelines-viewer/base',
              './pipeline/pipelines-runner/base', './pipeline/pipelines-ui/base',
              './pipeline/minio/base', './katib-v1alpha1/studyjob/base',
              './katib-v1alpha1/vizier-db/base',
              './katib-v1alpha1/suggestion/base',
              './katib-v1alpha1/katib-ui/base',
              './katib-v1alpha1/metrics-collector/base',
              './katib-v1alpha1/vizier-core/base',
              './pytorch-job/pytorch-job-crds/base',
              './pytorch-job/pytorch-operator/base', './istio/istio/base',
              './istio/istio-install/base', './istio/istio-crds/base',
              './tf-training/tf-job-operator/base',
              './katib-v1alpha2/katib-db/base',
              './katib-v1alpha2/katib-manager/base',
              './katib-v1alpha2/suggestion/base',
              './katib-v1alpha2/katib-ui/base',
              './katib-v1alpha2/katib-controller/base',
              './katib-v1alpha2/metrics-collector/base', './modeldb/base',
              './seldon/seldon-core-operator/base', './common/basic-auth/base',
              './common/spartakus/base', './common/centraldashboard/base',
              './common/ambassador/base', './kubebench/base',
              './argo/base', './tensorboard/base',
              './profiles/base', './admission-webhook/bootstrap/base',
              './admission-webhook/webhook/base', './metadata/base',
              './application/application-crds/base',
              './application/application/base',
              './jupyter/notebook-controller/base',
              './jupyter/jupyter-web-app/base', './jupyter/jupyter/base',
              './metacontroller/base', './gcp/basic-auth-ingress/base',
              './gcp/cloud-endpoints/base', './gcp/prometheus/base',
              './gcp/gpu-driver/base', './gcp/iap-ingress/base']
for fxname in yaml_files:
    filename = os.path.join(data_dir, fxname)
    cmd = "kubectl kustomize %s" % (filename)
    # print(cmd)
    with os.popen(cmd) as fr:
        with open(f"{data_dir}/yaml/{fxname.split('/')[-2]}.yaml", "w") as fw:
            data = fr.read()
            print(data)
            fw.write(data)
    # break
```

**Comment by eastlunar** [comment]
@ald2004 你好，请问您知道是什么时候yaml的镜像被替换成了国内阿里云的镜像吗，具体是哪个指令哪些文件做到的呢？

**Comment by shikanon** [comment]
> @ald2004 你好，请问您知道是什么时候yaml的镜像被替换成了国内阿里云的镜像吗，具体是哪个指令哪些文件做到的呢？

自己写了个替换脚本 🐶
