### ISSUE TITLE
报错,“namespaces "kubeflow" not found”,好像是找不到这个namespaces

### ISSUE THREAD

**Issue by chengjie-dc** [shikanon/kubeflow-manifests#6]
Error from server (NotFound): error when creating "tf-job-operator.yaml": namespaces "kubeflow" not found
Error from server (NotFound): error when creating "tf-job-operator.yaml": namespaces "kubeflow" not found
Error from server (NotFound): error when creating "webhook.yaml": namespaces "kubeflow" not found
Error from server (NotFound): error when creating "webhook.yaml": namespaces "kubeflow" not found
Error from server (NotFound): error when creating "webhook.yaml": namespaces "kubeflow" not found
Error from server (NotFound): error when creating "webhook.yaml": namespaces "kubeflow" not found
[unable to recognize "application.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1", unable to recognize "argo.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3", unable to recognize "centraldashboard.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3", unable to recognize "istio-install.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "istio-install.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "istio-install.yaml": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2", unable to recognize "istio-install.yaml": no matches for kind "logentry" in version "config.istio.io/v1alpha2", unable to recognize "istio-install.yaml": no matches for kind "metric" in version "config.istio.io/v1alpha2", unable to recognize "istio-install.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "istio-install.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "istio.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "istio.yaml": no matches for kind "ServiceEntry" in version "networking.istio.io/v1alpha3", unable to recognize "istio.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3", unable to recognize "istio.yaml": no matches for kind "ClusterRbacConfig" in version "rbac.istio.io/v1alpha1", unable to recognize "jupyter-web-app.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1", unable to recognize "jupyter-web-app.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3", unable to recognize "katib-ui.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3", unable to recognize "metadata.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3", unable to recognize "notebook-controller.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1", unable to rNo resources found.

**Comment by CrazyRobben** [comment]
自己手动创建一个命名空间

**Comment by shikanon** [comment]
看你的错误应该是没有命名空间kubeflow:
```
 kubectl create namespace kubeflow
```

**Comment by chengjie-dc** [comment]
> 看你的错误应该是没有命名空间kubeflow，可以手动创建:
> 
> ```
>  kubectl create namespace kubeflow
> ```
上次的解决了,命名空间的问题,
脚本执行之后, 发现,很多pod 没起来了...
[root@k8s-master01 ~]# kubectl get pods --namespace kubeflow
NAME                                                        READY   STATUS              RESTARTS   AGE
admission-webhook-bootstrap-stateful-set-0                  1/1     Running             0          23h
admission-webhook-deployment-5bc8bb7bf5-zv97z               0/1     ContainerCreating   0          23h
application-controller-stateful-set-0                       0/1     ContainerCreating   0          23h
argo-ui-6db54c878-6wmbf                                     1/1     Running             0          23h
centraldashboard-799bddbb96-sw97k                           0/1     ContainerCreating   0          23h
jupyter-web-app-deployment-5cc8f4d974-cvmhc                 1/1     Running             0          23h
katib-controller-7d6b69686d-kfmr5                           1/1     Running             1          23h
katib-db-b48df7777-5whph                                    0/1     Pending             0          23h
katib-manager-5b4fd464f4-t8xm6                              0/1     ContainerCreating   0          23h
katib-manager-rest-7cd4fc76cb-7fktt                         1/1     Running             0          23h
katib-suggestion-bayesianoptimization-59577ccf75-p6cp4      1/1     Running             0          23h
katib-suggestion-grid-589759cddd-vxj7w                      1/1     Running             0          23h
katib-suggestion-hyperband-7db5445544-52pv9                 1/1     Running             0          23h
katib-suggestion-nasrl-5865dfd7cd-6qzs7                     1/1     Running             0          23h
katib-suggestion-random-56999c7d9d-lwmvp                    1/1     Running             0          23h
katib-ui-65f85458c8-g7bfw                                   1/1     Running             0          23h
metacontroller-0                                            0/1     ContainerCreating   0          23h
metadata-db-8d9b95598-n4wqf                                 0/1     Pending             0          23h
metadata-deployment-65b5f4cf-c4dkw                          0/1     CrashLoopBackOff    277        23h
metadata-deployment-65b5f4cf-dmsjx                          0/1     CrashLoopBackOff    277        23h
metadata-deployment-65b5f4cf-xnf8h                          0/1     ContainerCreating   0          23h
metadata-ui-7794cf68d5-d5ff8                                1/1     Running             0          23h
minio-56dc668bd-whhjh                                       0/1     Pending             0          23h
ml-pipeline-69bf75d8cd-52nrn                                0/1     ContainerCreating   0          23h
ml-pipeline-persistenceagent-66fbcdf6d9-dd2xl               0/1     CrashLoopBackOff    188        23h
ml-pipeline-scheduledworkflow-65476754cf-8kcbw              1/1     Running             0          23h
ml-pipeline-ui-6d68b74f4c-r5sjk                             1/1     Running             0          23h
ml-pipeline-viewer-controller-deployment-6c589c59c9-bs4nc   1/1     Running             0          23h
mysql-75654987c5-pqsmg                                      0/1     Pending             0          23h
notebook-controller-deployment-7d4c6b4d96-2k9wc             1/1     Running             0          23h
profiles-deployment-55bbfcc7fb-24kpl                        2/2     Running             0          23h
pytorch-operator-6ccf47bcb-kwg4n                            1/1     Running             0          23h
seldon-operator-controller-manager-0                        1/1     Running             1          23h
spartakus-volunteer-7bfb86c64b-xsw8l                        1/1     Running             0          23h
tensorboard-5f685f9d79-ws658                                0/1     ContainerCreating   0          23h
tf-job-dashboard-789f5f67b5-v5dt6                           0/1     ContainerCreating   0          23h
tf-job-operator-76f88c78bd-kwnkn                            1/1     Running             0          23h
workflow-controller-5b4764bc47-c9zxn                        0/1     ContainerCreating   0          23h
[root@k8s-master01 ~]#

**Comment by chengjie-dc** [comment]
> 看你的错误应该是没有命名空间kubeflow，可以手动创建:
> 
> ```
>  kubectl create namespace kubeflow
> ```
上次的解决了,命名空间的问题,
脚本执行之后, 发现,很多pod 没起来了...



[root@k8s-master01 ~]# kubectl get pods --namespace kubeflow
NAME                                                        READY   STATUS              RESTARTS   AGE
admission-webhook-bootstrap-stateful-set-0                  1/1     Running             0          23h
admission-webhook-deployment-5bc8bb7bf5-zv97z               0/1     ContainerCreating   0          23h
application-controller-stateful-set-0                       0/1     ContainerCreating   0          23h
argo-ui-6db54c878-6wmbf                                     1/1     Running             0          23h
centraldashboard-799bddbb96-sw97k                           0/1     ContainerCreating   0          23h
jupyter-web-app-deployment-5cc8f4d974-cvmhc                 1/1     Running             0          23h
katib-controller-7d6b69686d-kfmr5                           1/1     Running             1          23h
katib-db-b48df7777-5whph                                    0/1     Pending             0          23h
katib-manager-5b4fd464f4-t8xm6                              0/1     ContainerCreating   0          23h
katib-manager-rest-7cd4fc76cb-7fktt                         1/1     Running             0          23h
katib-suggestion-bayesianoptimization-59577ccf75-p6cp4      1/1     Running             0          23h
katib-suggestion-grid-589759cddd-vxj7w                      1/1     Running             0          23h
katib-suggestion-hyperband-7db5445544-52pv9                 1/1     Running             0          23h
katib-suggestion-nasrl-5865dfd7cd-6qzs7                     1/1     Running             0          23h
katib-suggestion-random-56999c7d9d-lwmvp                    1/1     Running             0          23h
katib-ui-65f85458c8-g7bfw                                   1/1     Running             0          23h
metacontroller-0                                            0/1     ContainerCreating   0          23h
metadata-db-8d9b95598-n4wqf                                 0/1     Pending             0          23h
metadata-deployment-65b5f4cf-c4dkw                          0/1     CrashLoopBackOff    277        23h
metadata-deployment-65b5f4cf-dmsjx                          0/1     CrashLoopBackOff    277        23h
metadata-deployment-65b5f4cf-xnf8h                          0/1     ContainerCreating   0          23h
metadata-ui-7794cf68d5-d5ff8                                1/1     Running             0          23h
minio-56dc668bd-whhjh                                       0/1     Pending             0          23h
ml-pipeline-69bf75d8cd-52nrn                                0/1     ContainerCreating   0          23h
ml-pipeline-persistenceagent-66fbcdf6d9-dd2xl               0/1     CrashLoopBackOff    188        23h
ml-pipeline-scheduledworkflow-65476754cf-8kcbw              1/1     Running             0          23h
ml-pipeline-ui-6d68b74f4c-r5sjk                             1/1     Running             0          23h
ml-pipeline-viewer-controller-deployment-6c589c59c9-bs4nc   1/1     Running             0          23h
mysql-75654987c5-pqsmg                                      0/1     Pending             0          23h
notebook-controller-deployment-7d4c6b4d96-2k9wc             1/1     Running             0          23h
profiles-deployment-55bbfcc7fb-24kpl                        2/2     Running             0          23h
pytorch-operator-6ccf47bcb-kwg4n                            1/1     Running             0          23h
seldon-operator-controller-manager-0                        1/1     Running             1          23h
spartakus-volunteer-7bfb86c64b-xsw8l                        1/1     Running             0          23h
tensorboard-5f685f9d79-ws658                                0/1     ContainerCreating   0          23h
tf-job-dashboard-789f5f67b5-v5dt6                           0/1     ContainerCreating   0          23h
tf-job-operator-76f88c78bd-kwnkn                            1/1     Running             0          23h
workflow-controller-5b4764bc47-c9zxn                        0/1     ContainerCreating   0          23h

**Comment by chengjie-dc** [comment]
报错信息:admission-webhook-deployment-5bc8bb7bf5-zv97z 


Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-04-26T09:22:54Z"
  generateName: admission-webhook-deployment-5bc8bb7bf5-
  labels:
    app: admission-webhook
    kustomize.component: admission-webhook
    pod-template-hash: 5bc8bb7bf5
  name: admission-webhook-deployment-5bc8bb7bf5-zv97z
  namespace: kubeflow
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: admission-webhook-deployment-5bc8bb7bf5
    uid: f64fe003-9286-4e5f-a5d1-4e4350c169c2
  resourceVersion: "4973642"
  selfLink: /api/v1/namespaces/kubeflow/pods/admission-webhook-deployment-5bc8bb7bf5-zv97z
  uid: 75612998-f0f3-46eb-9b18-a2db1d752248
spec:
  containers:
  - image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.admission-webhook:v20190520-v0-139-gcee39dbc-dirty-0d8f4c
    imagePullPolicy: IfNotPresent
    name: admission-webhook
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/webhook/certs
      name: webhook-cert
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: admission-webhook-service-account-token-rq4g8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-node02







  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: admission-webhook-service-account
  serviceAccountName: admission-webhook-service-account
terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: webhook-cert
    secret:
      defaultMode: 420
      secretName: webhook-certs
  - name: admission-webhook-service-account-token-rq4g8
    secret:
      defaultMode: 420
      secretName: admission-webhook-service-account-token-rq4g8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-04-26T09:22:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-04-26T09:22:54Z"
    message: 'containers with unready status: [admission-webhook]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-04-26T09:22:54Z"
    message: 'containers with unready status: [admission-webhook]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-04-26T09:22:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: registry.cn-shenzhen.aliyuncs.com/shikanon/kubeflow-images-public.admission-webhook:v20190520-v0-139-gcee39dbc-dirty-0d8f4c
    imageID: ""
    lastState: {}
    name: admission-webhook
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 10.0.103.200
  phase: Pending
  qosClass: BestEffort
  startTime: "2020-04-26T09:22:54Z"

**Comment by CrazyRobben** [comment]
有Pending状态的应该是没有安装本地持久化储存，去local-path目录下执行：kubectl apply -f local-path-storage.yaml   就行

**Comment by shikanon** [comment]
没起来你可以通过`kubectl logs`或者`kubectl describe pod`查看错误原因，只有`CrashLoopBackOff`是无法分析的
