### ISSUE TITLE
(非kind安装)Pod无法完全起来[waiting for a volume to be created, either by external provisioner "rancher.io/local-path"]

### ISSUE THREAD

**Issue by Corezcy** [shikanon/kubeflow-manifests#60]
在单独安装docker/ k8s后，使用install.py安装kubeflow后，pod状态如：
```
kubectl get pod -A
NAMESPACE          NAME                                       READY   STATUS              RESTARTS   AGE
auth               dex-68b9bb7889-7t5zp                       1/1     Running             0          107m
cert-manager       cert-manager-649f8dfd4b-bp8hh              1/1     Running             0          4h39m
cert-manager       cert-manager-cainjector-75cd8bbf6d-hpnkn   1/1     Running             0          4h39m
cert-manager       cert-manager-webhook-5b5cd9bd6f-dqjkq      1/1     Running             1          4h39m
istio-system       authservice-0                              0/1     Pending             0          4h38m
istio-system       cluster-local-gateway-74d9fd9586-prw4v     0/1     ContainerCreating   0          107m
istio-system       istio-ingressgateway-8bf685655-6s6bn       0/1     ContainerCreating   0          107m
istio-system       istiod-6f99d55d99-bqln5                    0/1     Running             2          2m40s
istio-system       istiod-756554b96b-8l49j                    0/1     CrashLoopBackOff    21         107m
knative-eventing   broker-controller-cfb5ccb77-hrjtf          1/1     Running             0          4h37m
knative-eventing   eventing-controller-8657cd4b8-t65gk        1/1     Running             0          4h37m
knative-eventing   eventing-webhook-67f86f4d4d-zwh9g          0/1     CrashLoopBackOff    45         4h37m
knative-eventing   imc-controller-68bd666784-4qw6d            1/1     Running             0          4h37m
knative-eventing   imc-dispatcher-78ff9dd847-f7gkp            0/1     CrashLoopBackOff    45         4h37m
knative-serving    activator-54b777546f-dp47d                 1/1     Running             0          4h37m
knative-serving    autoscaler-79bbc84d47-jbqzj                1/1     Running             0          4h37m
knative-serving    controller-dd65cb4b7-wrwbd                 1/1     Running             0          4h37m
knative-serving    istio-webhook-5f545fc44b-7j2bg             0/1     CrashLoopBackOff    45         4h37m
knative-serving    networking-istio-6b6df495d6-44wzr          1/1     Running             0          4h37m
knative-serving    webhook-9ff656f95-mzhj6                    1/1     Running             0          4h37m
kube-system        coredns-54d67798b7-9tvk6                   1/1     Running             25         227d
kube-system        coredns-54d67798b7-wqsts                   1/1     Running             27         227d
kube-system        etcd-k8s-master01                          1/1     Running             26         227d
kube-system        kube-apiserver-k8s-master01                1/1     Running             322        227d
kube-system        kube-controller-manager-k8s-master01       1/1     Running             32         226d
kube-system        kube-flannel-ds-jdh7f                      1/1     Running             3562       226d
kube-system        kube-flannel-ds-jssrl                      1/1     Running             1          46h
kube-system        kube-flannel-ds-lkqzd                      1/1     Running             41         225d
kube-system        kube-proxy-76c8r                           1/1     Running             1          46h
kube-system        kube-proxy-9z7jf                           1/1     Running             16         183d
kube-system        kube-proxy-tnzqv                           1/1     Running             26         180d
kube-system        kube-scheduler-k8s-master01                1/1     Running             32         226d
kube-system        metrics-server-v0.3.6-876b95bc8-jfjzj      2/2     Running             49         224d
tigera-operator    tigera-operator-7c5d47c4b5-kq2nm           1/1     Running             3          46h
```
istio-ingressgateway-8bf685655-6s6bn没有起来的原因：
```
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  48m (x5 over 87m)      kubelet  Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istio-data podinfo ingressgateway-certs ingressgateway-ca-certs istio-ingressgateway-service-account-token-8zpw8 istio-envoy config-volume istiod-ca-cert]: timed out waiting for the condition
  Warning  FailedMount  19m (x4 over 103m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[config-volume istiod-ca-cert istio-data podinfo ingressgateway-certs ingressgateway-ca-certs istio-ingressgateway-service-account-token-8zpw8 istio-envoy]: timed out waiting for the condition
  Warning  FailedMount  7m54s (x4 over 71m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert], unattached volumes=[istiod-ca-cert istio-data podinfo ingressgateway-certs ingressgateway-ca-certs istio-ingressgateway-service-account-token-8zpw8 istio-envoy config-volume]: timed out waiting for the condition
  Warning  FailedMount  3m46s (x60 over 109m)  kubelet  MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
```
**Other**:
```
kubectl get mutatingwebhookconfigurations -A
NAME                                               WEBHOOKS   AGE
admission-webhook-mutating-webhook-configuration   1          44h
cert-manager-webhook                               1          44h
inferenceservice.serving.kubeflow.org              3          44h
istio-sidecar-injector                             1          44h
katib.kubeflow.org                                 2          44h
sinkbindings.webhook.sources.knative.dev           1          44h
webhook.eventing.knative.dev                       1          44h
webhook.istio.networking.internal.knative.dev      1          44h
webhook.serving.knative.dev                        1          44h
```
查了一天的帖子，实在是不知道从哪改了，求教！！！

**Comment by Corezcy** [comment]
```shell
$ kubectl get pvc -A
NAMESPACE      NAME              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
istio-system   authservice-pvc   Pending                                                     21h
kubeflow       katib-mysql       Pending                                                     21h
kubeflow       minio-pvc         Pending                                                     21h
kubeflow       mysql-pv-claim    Pending                                                     21h
```

使用kubectl describe查询log都显示

```shell
Events:
  Type    Reason         Age                     From                         Message
  ----    ------         ----                    ----                         -------
  Normal  FailedBinding  3m43s (x5123 over 21h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```
您知道是什么原因吗？

**Comment by shikanon** [comment]
@Corezcy 你这是PVC问题，你如果是用kind安装的吗？如果不是你可以安装`/local-path`下面的 local-path-storage 作为默认 storageclass

**Comment by Corezcy** [comment]
> @Corezcy 你这是PVC问题，你是用kind安装的吗？如果不是你可以安装`/local-path`下面的 local-path-storage 作为默认 storageclass

不是kind安装的，直接安装K8s。好的，我先试试

**Comment by Corezcy** [comment]
执行 `python install.py` 的时候，出现以下错误：
```shell
Error from server (NotFound): error when creating "./manifest1.3/033-user-namespace-user-namespace-base.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
b'configmap/default-install-config-9h2h2b6hbk created\n'
start to patch...
Error from server (NotFound): error when deleting "./patch/auth.yaml": the server could not find the requested resource (delete profiles.kubeflow.org kubeflow-user-example-com)
b'configmap "dex" deleted\ndeployment.apps "dex" deleted\nconfigmap "default-install-config-9h2h2b6hbk" deleted\n'
Error from server (NotFound): error when creating "./patch/auth.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
b'configmap/dex created\ndeployment.apps/dex created\nconfigmap/default-install-config-9h2h2b6hbk created\n'
```
请问这个碍事吗？
我已经把local-path-storage 作为默认 storageclass并卸载重新安装，还是不行，难受。

**Comment by Corezcy** [comment]
![lADPD2sQwe5lsvfNDY_NA-o_1002_3471](https://user-images.githubusercontent.com/33271784/131292840-d6675c4d-dcfd-497a-b5c1-878d62503525.jpg)
感觉可能是这个问题。

**Comment by ds862** [comment]
> @Corezcy 你这是PVC问题，你是用kind安装的吗？如果不是你可以安装`/local-path`下面的 local-path-storage 作为默认 storageclass

请问` kubectl apply -f local-path-storage.yaml`后，执行`kubectl get pvc -A`，发现所有的pvc都在pending:

NAMESPACE      NAME              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
istio-system   authservice-pvc   Pending                                      local-path     7m55s
kubeflow       katib-mysql       Pending                                      local-path     5m49s
kubeflow       minio-pvc         Pending                                      local-path     6m10s
kubeflow       mysql-pv-claim    Pending                                      local-path     6m10s

`kubectl describe pvc authservice-pvc -nistio-system`查看pvc:
Name:          authservice-pvc
Namespace:     istio-system
StorageClass:  local-path
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
               volume.kubernetes.io/selected-node: iz8vb5qemr6glj4sj3kc0gz
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       authservice-0
Events:
  Type    Reason                Age                     From                         Message
  ----    ------                ----                    ----                         -------
  Normal  WaitForFirstConsumer  8m19s                   persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning  2m30s (x25 over 8m19s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator

**Comment by Corezcy** [comment]
> > @Corezcy 你这是PVC问题，你是用kind安装的吗？如果不是你可以安装`/local-path`下面的 local-path-storage 作为默认 storageclass
> 
> 请问` kubectl apply -f local-path-storage.yaml`后，执行`kubectl get pvc -A`，发现所有的pvc都在pending:
> 
> NAMESPACE NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
> istio-system authservice-pvc Pending local-path 7m55s
> kubeflow katib-mysql Pending local-path 5m49s
> kubeflow minio-pvc Pending local-path 6m10s
> kubeflow mysql-pv-claim Pending local-path 6m10s
> 
> `kubectl describe pvc authservice-pvc -nistio-system`查看pvc:
> Name: authservice-pvc
> Namespace: istio-system
> StorageClass: local-path
> Status: Pending
> Volume:
> Labels:
> Annotations: volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
> volume.kubernetes.io/selected-node: iz8vb5qemr6glj4sj3kc0gz
> Finalizers: [kubernetes.io/pvc-protection]
> Capacity:
> Access Modes:
> VolumeMode: Filesystem
> Used By: authservice-0
> Events:
> Type Reason Age From Message
> 
> Normal WaitForFirstConsumer 8m19s persistentvolume-controller waiting for first consumer to be created before binding
> Normal ExternalProvisioning 2m30s (x25 over 8m19s) persistentvolume-controller waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator

和我的错误一模一样，但是我还是不知道如何修改……，请问你有啥思路吗？

**Comment by ds862** [comment]
> > > @Corezcy 你这是PVC问题，你是用kind安装的吗？如果不是你可以安装`/local-path`下面的 local-path-storage 作为默认 storageclass
> > 
> > 
> > 请问` kubectl apply -f local-path-storage.yaml`后，执行`kubectl get pvc -A`，发现所有的pvc都在pending:
> > NAMESPACE NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
> > istio-system authservice-pvc Pending local-path 7m55s
> > kubeflow katib-mysql Pending local-path 5m49s
> > kubeflow minio-pvc Pending local-path 6m10s
> > kubeflow mysql-pv-claim Pending local-path 6m10s
> > `kubectl describe pvc authservice-pvc -nistio-system`查看pvc:
> > Name: authservice-pvc
> > Namespace: istio-system
> > StorageClass: local-path
> > Status: Pending
> > Volume:
> > Labels:
> > Annotations: volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
> > volume.kubernetes.io/selected-node: iz8vb5qemr6glj4sj3kc0gz
> > Finalizers: [kubernetes.io/pvc-protection]
> > Capacity:
> > Access Modes:
> > VolumeMode: Filesystem
> > Used By: authservice-0
> > Events:
> > Type Reason Age From Message
> > Normal WaitForFirstConsumer 8m19s persistentvolume-controller waiting for first consumer to be created before binding
> > Normal ExternalProvisioning 2m30s (x25 over 8m19s) persistentvolume-controller waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
> 
> 和我的错误一模一样，但是我还是不知道如何修改……，请问你有啥思路吗？
> 
> 还有一个问题，你的K8s是用kind装的吗？

不是用kind装的k8s。我在尝试设置一个nfs的默认存储类，不知道是否可行

**Comment by Corezcy** [comment]
> 设置一个nfs的默认存储类

我这边设置一个nfs的默认存储类，已经可以啦！

**Comment by ds862** [comment]
> > 设置一个nfs的默认存储类
> 
> 我这边设置一个nfs的默认存储类，已经可以啦！
> ![Screenshot-20210830163012-3712x1816](https://user-images.githubusercontent.com/33271784/131310499-8ad6b34a-8bc1-48dd-931d-63a416a43506.png)

请问你有设置成功的教程吗，我在网上找的教程，但是设置后没有自动创建pv

**Comment by Corezcy** [comment]
在另一台电脑（作为node）上，配置nfs，然后joinmaster，https://www.cnblogs.com/dakewei/p/11716270.html

**Comment by Corezcy** [comment]
> @Corezcy 你这是PVC问题，你是用kind安装的吗？如果不是你可以安装`/local-path`下面的 local-path-storage 作为默认 storageclass

十分感谢您的解答！

**Comment by mhh12121** [comment]
> 执行 `python install.py` 的时候，出现以下错误：
> 
> ```shell
> Error from server (NotFound): error when creating "./manifest1.3/033-user-namespace-user-namespace-base.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
> b'configmap/default-install-config-9h2h2b6hbk created\n'
> start to patch...
> Error from server (NotFound): error when deleting "./patch/auth.yaml": the server could not find the requested resource (delete profiles.kubeflow.org kubeflow-user-example-com)
> b'configmap "dex" deleted\ndeployment.apps "dex" deleted\nconfigmap "default-install-config-9h2h2b6hbk" deleted\n'
> Error from server (NotFound): error when creating "./patch/auth.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
> b'configmap/dex created\ndeployment.apps/dex created\nconfigmap/default-install-config-9h2h2b6hbk created\n'
> ```
> 
> 请问这个碍事吗？ 我已经把local-path-storage 作为默认 storageclass并卸载重新安装，还是不行，难受。

这个应该是PVC问题，作者的local-path-storage.yaml版本好像删掉了一些helperPod的东西，与你当前使用的环境(非kind安装k8s) 可能不适配，可以去[rancher仓库](https://github.com/rancher/local-path-provisioner) 下载一个新的尝试一下； 我在单机下kubeadm安装的k8s也出现这种问题，暂时使用这个解决；

**Comment by wenyangzz** [comment]
> > 执行 `python install.py` 的时候，出现以下错误：
> > ```shell
> > Error from server (NotFound): error when creating "./manifest1.3/033-user-namespace-user-namespace-base.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
> > b'configmap/default-install-config-9h2h2b6hbk created\n'
> > start to patch...
> > Error from server (NotFound): error when deleting "./patch/auth.yaml": the server could not find the requested resource (delete profiles.kubeflow.org kubeflow-user-example-com)
> > b'configmap "dex" deleted\ndeployment.apps "dex" deleted\nconfigmap "default-install-config-9h2h2b6hbk" deleted\n'
> > Error from server (NotFound): error when creating "./patch/auth.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
> > b'configmap/dex created\ndeployment.apps/dex created\nconfigmap/default-install-config-9h2h2b6hbk created\n'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问这个碍事吗？ 我已经把local-path-storage 作为默认 storageclass并卸载重新安装，还是不行，难受。
> 
> 这个应该是PVC问题，作者的local-path-storage.yaml版本好像删掉了一些helperPod的东西，与你当前使用的环境(非kind安装k8s) 可能不适配，可以去[rancher仓库](https://github.com/rancher/local-path-provisioner) 下载一个新的尝试一下； 我在单机下kubeadm安装的k8s也出现这种问题，暂时使用这个解决；
您好！

> 在另一台电脑（作为node）上，配置nfs，然后joinmaster，https://www.cnblogs.com/dakewei/p/11716270.html

请问您配置nfs后，还需要执行apply -f local-path-storage.yaml这个嘛

**Comment by YeeHen** [comment]
> > > 执行 `python install.py` 的时候，出现以下错误：
> > > ```shell
> > > Error from server (NotFound): error when creating "./manifest1.3/033-user-namespace-user-namespace-base.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
> > > b'configmap/default-install-config-9h2h2b6hbk created\n'
> > > start to patch...
> > > Error from server (NotFound): error when deleting "./patch/auth.yaml": the server could not find the requested resource (delete profiles.kubeflow.org kubeflow-user-example-com)
> > > b'configmap "dex" deleted\ndeployment.apps "dex" deleted\nconfigmap "default-install-config-9h2h2b6hbk" deleted\n'
> > > Error from server (NotFound): error when creating "./patch/auth.yaml": the server could not find the requested resource (post profiles.kubeflow.org)
> > > b'configmap/dex created\ndeployment.apps/dex created\nconfigmap/default-install-config-9h2h2b6hbk created\n'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 请问这个碍事吗？ 我已经把local-path-storage 作为默认 storageclass并卸载重新安装，还是不行，难受。
> > 
> > 
> > 这个应该是PVC问题，作者的local-path-storage.yaml版本好像删掉了一些helperPod的东西，与你当前使用的环境(非kind安装k8s) 可能不适配，可以去[rancher仓库](https://github.com/rancher/local-path-provisioner) 下载一个新的尝试一下； 我在单机下kubeadm安装的k8s也出现这种问题，暂时使用这个解决；
> > 您好！
> 
> > 在另一台电脑（作为node）上，配置nfs，然后joinmaster，https://www.cnblogs.com/dakewei/p/11716270.html
> 
> 请问您配置nfs后，还需要执行apply -f local-path-storage.yaml这个嘛

我使用这种方法 okay 了。更新了下 local-path-storage.yaml
