### ISSUE TITLE
Error from server (Forbidden): error when creating "./manifest1.3/016-istio-1-9-0-kubeflow-istio-resources-base.yaml": gateways.networking.istio.io "kubeflow-gateway" is forbidden: unable to create new content in namespace kubeflow because it is being terminated

### ISSUE THREAD

**Issue by longpi1** [shikanon/kubeflow-manifests#65]
请问出现一下报错是什么原因呢？
kubectl apply -f ./manifest1.3/016-istio-1-9-0-kubeflow-istio-resources-base.yaml
Error from server (Forbidden): error when creating "./manifest1.3/016-istio-1-9-0-kubeflow-istio-resources-base.yaml": gateways.networking.istio.io "kubeflow-gateway" is forbidden: unable to create new content in namespace kubeflow because it is being terminated
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-admin created
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-edit created
clusterrole.rbac.authorization.k8s.io/kubeflow-istio-view created

kubectl apply -f ./manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml
Error from server (Forbidden): error when creating "./manifest1.3/017-pipeline-env-platform-agnostic-multi-user.yaml": serviceaccounts "argo" is forbidden: unable to create new content in namespace kubeflow because it is being terminated
customresourcedefinition.apiextensions.k8s.io/clusterworkflowtemplates.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/compositecontrollers.metacontroller.k8s.io created
customresourcedefinition.apiextensions.k8s.io/controllerrevisions.metacontroller.k8s.io created
customresourcedefinition.apiextensions.k8s.io/cronworkflows.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/decoratorcontrollers.metacontroller.k8s.io created
customresourcedefinition.apiextensions.k8s.io/scheduledworkflows.kubeflow.org created
customresourcedefinition.apiextensions.k8s.io/viewers.kubeflow.org created
customresourcedefinition.apiextensions.k8s.io/workfloweventbindings.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/workflows.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/workflowtemplates.argoproj.io created

kubectl apply -f ./manifest1.3/018-kfserving-overlays-kubeflow.yaml
Error from server (Forbidden): error when creating "./manifest1.3/018-kfserving-overlays-kubeflow.yaml": roles.rbac.authorization.k8s.io "leader-election-role" is forbidden: unable to create new content in namespace kubeflow because it is being terminated
customresourcedefinition.apiextensions.k8s.io/inferenceservices.serving.kubeflow.org created
customresourcedefinition.apiextensions.k8s.io/trainedmodels.serving.kubeflow.org created

**Comment by shikanon** [comment]
@longpi1 看日志应该是你的kubeflow空间删除失败，一直处于 terminated 中。

**Comment by Patarw** [comment]
> 

您好，我也遇到了与这个一样的问题，请问这个问题要怎样解决呢

**Comment by longpi1** [comment]
> > 
> 
> 您好，我也遇到了与这个一样的问题，请问这个问题要怎样解决呢

忘记了兄弟，实在不行去etcd把这个命名空间删除

**Comment by Patarw** [comment]
> > > 
> > 
> > 
> > 您好，我也遇到了与这个一样的问题，请问这个问题要怎样解决呢
> 
> 忘记了兄弟，实在不行去etcd把这个命名空间删除

好吧，谢谢兄弟
