### ISSUE TITLE
数据库连接问题

### ISSUE THREAD

**Issue by wxuxu** [shikanon/kubeflow-manifests#7]
有几个需要连接到mysql数据库的组件，都出现了running状态，但ready为0（False），查看events，发现是连接不上数据库
Events:
  Type     Reason     Age                    From                         Message
  ----     ------     ----                   ----                         -------
  Warning  Unhealthy  85s (x50399 over 28h)  kubelet, kind-control-plane  Readiness probe failed: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

进入到对应容器里，在容器里也无法连接到数据库。因为是个docker小白，很多操作不懂，在容器里面很多命令发现都运行不了，无法像在正常系统中操作，不知怎么解决。

kubectl版本是1.15的，是符合0.6版本的要求的
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2020-01-14T00:28:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by wxuxu** [comment]
几个数据库相关的pod，需要自己修改环境变量的值吗？感觉问题主要都出现在数据库相关的pod上

**Comment by shikanon** [comment]
哪个pod连接不到数据库，是不是网络问题，你可以通过`kubectl logs`排查下

**Comment by wxuxu** [comment]
> 哪个pod连接不到数据库，是不是网络问题，你可以通过`kubectl logs`排查下

你好，感谢回复，是这两个pod（katib-db，metadata-db）连接不上数据库，而且，后面这几个pod（mysql，katib-db，metadata-db，metadata-deployment）又变成了CrashLoopBackOff状态了，
其中，mysql的logs如下：
2020-05-07 01:17:33+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.48-1debian9 started.
2020-05-07 01:17:33+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
        command was: mysqld --verbose --help
        mysqld: error while loading shared libraries: libpthread.so.0: cannot stat shared object: Permission denied

katib-db和metadata-db的logs如下：
ERROR: mysqld failed while attempting to check config
command was: "mysqld --datadir /var/lib/mysql/datadir --verbose --help"
mysqld: error while loading shared libraries: libpthread.so.0: cannot stat shared object: Permission denied

metadata-deployment的logs如下：
F0507 01:24:53.463102       1 main.go:90] Failed to create ML Metadata Store with config mysql:<host:"metadata-db.kubeflow" port:3306 database:"metadb" user:"root" password:"test" > : mysql_real_connect failed: errno: 2002, error: Can't connect to MySQL server on 'metadata-db.kubeflow' (115).
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc00022a300, 0xc000236000, 0x126, 0x17c)
        external/com_github_golang_glog/glog.go:769 +0xb1
github.com/golang/glog.(*loggingT).output(0x1633360, 0xc000000003, 0xc00021e000, 0x14eadd3, 0x7, 0x5a, 0x0)
        external/com_github_golang_glog/glog.go:720 +0x2f6
github.com/golang/glog.(*loggingT).printf(0x1633360, 0x3, 0xf6fee1, 0x37, 0xc0001efe30, 0x2, 0x2)
        external/com_github_golang_glog/glog.go:655 +0x14e
github.com/golang/glog.Fatalf(...)
        external/com_github_golang_glog/glog.go:1148
main.mlmdStoreOrDie(0x0)
        server/main.go:90 +0x1c3
main.main()
        server/main.go:101 +0xe0

看起来，问题应该是类似的，里面提到了权限问题，但我不知道该怎么解决

**Comment by shikanon** [comment]
是不是没启本地pv啊，运行了`kubectl apply -f local-path-storage.yaml`这个吗？

**Comment by wxuxu** [comment]
感谢回复，本地pv是启动了的。
我想请问一下，服务器中本来就存在mysql数据库，是否会对该集群有影响呢？

**Comment by shikanon** [comment]
不会，k8s的服务是通过CNI确定具体访问哪个ip上的服务的，本地mysql服务监听的是127.0.0.1上的端口，不会影响到集群数据库

**Comment by wxuxu** [comment]
感谢回复，不过我觉得是会有影响的，我不确定是什么原因，是在这里看到的
https://github.com/moby/moby/issues/7512
然后，我把原来的数据库删除并重启电脑后，重新安装，之前的错误就都没有了，现在，全都是running状态了。使用端口转发后也能访问了。
另外，我还有个问题想请问一下，是可以通过哪个端口直接访问系统界面呢？看另一个issues，说到31380，但我访问了0.0.0.0:31380没反应，而且，使用netstat -nutlp 命令也没发现有kubectl的端口。
