### ISSUE TITLE
怎么可以公网访问可视化界面呢

### ISSUE THREAD

**Issue by utopfish** [shikanon/kubeflow-manifests#8]
您好，我在初学kubeflow，在网上就唯一找到您这样一个很方便下载的kubeflow方法，我看其他的方法里面有ambassador，然后通过LoadBalancer实现外网访问，我看您的里面没有ambassador那请问是如何实现外网访问可视化界面的呢？请多指教

**Comment by wxuxu** [comment]
sudo kubectl port-forward -n istio-system svc/istio-ingressgateway 80:80 --address 0.0.0.0
你可以试试这个，我在其他教程上看到的，把其中的第一个80改成你想访问的端口

**Comment by utopfish** [comment]
您好@wxuxu，感谢告知。我试过您说的这个方法了，https://blog.csdn.net/Tilyp/article/details/102547015这篇教程里的方法应该和您说的这个类似，但是我弄好之后还是有问题：
E0506 13:14:38.565258   15604 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod 282882f3898cf9b961486261a2ae1e6f9e3794b999601c07f1b5dc9c46fa0640, uid : exit status 1: 2020/05/06 13:14:38 socat[19601] E connect(9, AF=2 127.0.0.1:80, 16): Connection refused
报了这样一个连接被拒绝的错误，这可能是什么原因导致的呢

**Comment by wxuxu** [comment]
我刚运行安装命令不久的时候，访问也会出现类似你这样的错误，这个时候很多的pod都还在 创建  阶段，等大部分的pod都在running阶段时，再访问网站这个错误就没有了。所以我觉得你可能是有的pod还没有成功安装，你可以使用kubectl get pods 查看一下pod的状态，看看能否从这个方面解决。
因为我也是最近才开始学习和部署kubeflow，很多东西也是一知半解，不清楚里面深层的东西。

**Comment by utopfish** [comment]
嗯嗯，好的感谢，我下午重新租了一个更大的服务器，现在正在等服务running，我觉得您说的这个很有可能，我现在这里有一个情况是我用watch kubectl get pod -nkubeflow看，有一些服务出现ImagePullBackOff和 CrashLoopBackOff，这个有什么办法单独把这些服务重启吗？如果将全部重启的话，我这里可能需要花至少半小时的时间。

**Comment by wxuxu** [comment]
可以使用sudo kubectl delete -f xxx.yaml将有问题的pod删除，修改好之后，sudo kubectl apply -f xxx.yaml再重新添加该pod，这里，你可能就需要去找出想要重启的服务在哪一个.yaml文件中了

**Comment by utopfish** [comment]
嗯嗯 感谢，重启之后，所有的服务都好了，果然是之前服务器太小的原因，导致很多pod都无法启动。我刚刚是用kubeadm reset把整个k8s服务重启，但是cni的配置这些都没有删除，把服务重启之后，很有意思的是之前要花很多时间启动的pod很快就运行起来了，在一个screen里面用您最开始告知的那个命令我把kubeflow启动起来了

**Comment by wxuxu** [comment]
你好，能否告知一下，你这两次的服务器的配置吗，我自己部署的时候，也是遇到CrashLoopBackOff状态，还没有解决，而且每次启动pod也是需要很长时间。之前还真没考虑到是服务器问题，想大概了解一下，会不会确实是服务器的问题。

**Comment by utopfish** [comment]
开始用的是2核4g内存的，之后换成4核16g内存的，都用的是阿里云的服务器，确实CrashLoopBackOff这个情况我现在也只有重启服务来解决

**Comment by shikanon** [comment]
kubeflow组件里的pipeline-ui就是用的 ambassador ， 不需要单独安装，我这个是完全和官网安装是一样的，只是用国内镜像做了替换

**Comment by utopfish** [comment]
嗯嗯好的，感谢我的问题已经解决了，而且我刚刚把sudo kubectl port-forward -n istio-system svc/istio-ingressgateway 80:80 --address 0.0.0.0这个命令没有启动，也能正常访问，我最开始的问题应该是我之前服务器没能把所有服务启动的原因，所有pod都正常running的话，直接访问31380端口应该就能正常访问kubeflow界面了

**Comment by kangzhang0709** [comment]
> 嗯嗯好的，感谢我的问题已经解决了，而且我刚刚把sudo kubectl port-forward -n istio-system svc/istio-ingressgateway 80:80 --address 0.0.0.0这个命令没有启动，也能正常访问，我最开始的问题应该是我之前服务器没能把所有服务启动的原因，所有pod都正常running的话，直接访问31380端口应该就能正常访问kubeflow界面了

31380端口是哪里设置的？另外我的服务全部running之后，公网也访问不了UI，好奇怪。。。

**Comment by shikanon** [comment]
@kangzhang0709 你可以看看 `istio-ingressgateway` 这个 service 的 external-ip

**Comment by kangzhang0709** [comment]
> @kangzhang0709 你可以看看 `istio-ingressgateway` 这个 service 的 external-ip
貌似没有external-ip呀？
![image](https://user-images.githubusercontent.com/32809802/124410536-4ac4e400-dd7d-11eb-8701-cede7e479edf.png)

**Comment by shikanon** [comment]
@kangzhang0709 这个是 nodeport，你直接访问部署节点的30000端口就可以了

**Comment by kangzhang0709** [comment]
> @kangzhang0709 这个是 nodeport，你直接访问部署节点的30000端口就可以了

哈哈哈，确实可以打开DashBoard UI了。不过又遇到了no namespace的问题。。。
![image](https://user-images.githubusercontent.com/32809802/124427491-07c73880-dd9e-11eb-8702-15cf3cf00d47.png)

**Comment by shikanon** [comment]
no namespace 问题可以试试更新下 patch/auth.yaml 文件解决：
```yaml
kubectl delete -f patch/auth.yaml
kubectl apply -f patch/auth.yaml
```

**Comment by kangzhang0709** [comment]
> no namespace 问题可以试试更新下 patch/auth.yaml 文件解决：
> 
> ```yaml
> kubectl delete -f patch/auth.yaml
> kubectl apply -f patch/auth.yaml
> ```
太尴尬了。。。
![image](https://user-images.githubusercontent.com/32809802/124496697-5996af80-ddec-11eb-986e-43779ee42acc.png)

**Comment by kangzhang0709** [comment]
> > no namespace 问题可以试试更新下 patch/auth.yaml 文件解决：
> > ```yaml
> > kubectl delete -f patch/auth.yaml
> > kubectl apply -f patch/auth.yaml
> > ```
> 
> 太尴尬了。。。
> ![image](https://user-images.githubusercontent.com/32809802/124496697-5996af80-ddec-11eb-986e-43779ee42acc.png)

解决了，重新运行了：
kubectl apply -f manifest1.3/024-profiles-overlays-kubeflow.yaml
kubectl apply -f patch/auth.yaml
