### ISSUE TITLE
@ligh2012 这个kubeflow 的pipeline 就是用的 argo 实现的，你的pvc 如果一直在 pending ，说明应该是 storageClass 的问题，CSI没办法创建默认卷。如果想用官方的 pipeline 案例可以在基于 docker 的 k8s 上安装 kubeflow。

### ISSUE THREAD

**Issue by ligh2012** [shikanon/kubeflow-manifests#81]
@ligh2012 这个kubeflow 的pipeline 就是用的 argo 实现的，你的pvc 如果一直在 pending ，说明应该是 storageClass 的问题，CSI没办法创建默认卷。如果想用官方的 pipeline 案例可以在基于 docker 的 k8s 上安装 kubeflow。

_Originally posted by @shikanon in https://github.com/shikanon/kubeflow-manifests/issues/70#issuecomment-939289226_
1、您的意思是我解决了 storageClass 的问题，您提供的pipeline就可以运行了吗？
2、基于docker的k8s安装kubeflow就不能用阿里这个镜像吗？

**Comment by shikanon** [comment]
@ligh2012 不要开新问题，这样容易无厘头
