### ISSUE TITLE
pipeline执行出问题

### ISSUE THREAD

**Issue by markqiu** [shikanon/kubeflow-manifests#92]
目前可以通过kpf python sdk或者直接从Notebook中建立pipeline，提交可以成功，但pipeline运行会提示：k8sapi executor does not support outputs from base image layer。
请问如何解决？

**Comment by shikanon** [comment]
@markqiu kubeflow的pipline其实就是argo 的workflows，相关问题可以看看 argo 这文档：
https://github.com/argoproj/argo-workflows/blob/master/docs/workflow-executors.md

**Comment by markqiu** [comment]
谢谢 @shikanon
