### ISSUE TITLE
科学上网后是不是不能使用这个方法？

### ISSUE THREAD

**Issue by xiaogangzhu** [shikanon/kubeflow-manifests#95]
想问一下科学上网了，docker通过proxy映射，我使用python install.py最后是安装失败是什么原因呢

**Comment by shikanon** [comment]
> 想问一下科学上网了，docker通过proxy映射，我使用python install.py最后是安装失败是什么原因呢

科学上网了直接用官方提供的安装就好了，这个是用的阿里云仓库，提供给国内使用
